/**
 * Concatenate the resource-directory migration and seed into one file that
 * can be pasted into the Supabase dashboard's SQL editor.
 *
 * This is the credential-free way to install the directory: the applier
 * script needs a database password in .env.local, but the dashboard editor is
 * already authenticated in the browser.
 *
 * Usage: node scripts/build_install_sql.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const MIGRATION = 'supabase/migrations/008_resource_directory.sql';
const SEED = 'supabase/resources-seed.sql';
const OUT = 'supabase/resource-directory-install.sql';

const header = `-- ${'='.repeat(74)}
-- RESOURCE DIRECTORY — one-paste install.
--
-- This file is ${MIGRATION} followed by
-- ${SEED}, concatenated so it can be run in one go from
-- the Supabase dashboard when no local database credentials are available:
--
--   Supabase dashboard -> SQL Editor -> New query -> paste this file -> Run
--
-- Safe to run more than once. The migration is CREATE-IF-NOT-EXISTS
-- throughout, and the seed clears and rewrites only the two resource tables,
-- so re-running reproduces the current Resource Aid document exactly.
-- Nothing else in the database is touched.
--
-- Generated by scripts/gen_resources_seed.py — do not hand-edit. Regenerate
-- with: python3 scripts/gen_resources_seed.py && node scripts/build_install_sql.mjs
-- ${'='.repeat(74)}

`;

writeFileSync(
  OUT,
  header + readFileSync(MIGRATION, 'utf8').trimEnd() + '\n\n\n' + readFileSync(SEED, 'utf8').trimStart(),
);
console.log(`Wrote ${OUT}`);
