/**
 * Concatenate every migration the live database is still missing, plus the
 * resource-directory seed, into one file that can be pasted into the Supabase
 * dashboard's SQL editor.
 *
 * Same reasoning as build_install_sql.mjs — the applier scripts need a
 * database password in .env.local, the dashboard editor is already
 * authenticated in the browser — but scoped to the whole 005..008 gap rather
 * than the directory alone.
 *
 * Usage: node scripts/build_catchup_sql.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const PARTS = [
  'supabase/migrations/005_community_reports.sql',
  'supabase/migrations/006_org_read_own_applications.sql',
  'supabase/migrations/007_org_portal.sql',
  'supabase/migrations/008_resource_directory.sql',
  'supabase/resources-seed.sql',
];
const OUT = 'supabase/catch-up-install.sql';

const header = `-- ${'='.repeat(74)}
-- CATCH-UP INSTALL — migrations 005 through 008, plus the resource seed.
--
-- The live database stops after 004: community_reports, the organization
-- portal policies, and the two resource tables are all absent, which is why
-- the report form fails, the org portal has nothing to grant, and /resources
-- comes up empty. This file closes that gap in one paste:
--
--   Supabase dashboard -> SQL Editor -> New query -> paste this file -> Run
--
-- Safe to run more than once. Every statement is CREATE IF NOT EXISTS,
-- CREATE OR REPLACE, or DROP POLICY IF EXISTS followed by CREATE, and the
-- seed clears and rewrites only the two resource tables. Nothing that
-- FoodAssist depends on is dropped or rewritten.
--
-- Generated by scripts/build_catchup_sql.mjs — do not hand-edit.
-- ${'='.repeat(74)}

`;

const body = PARTS.map((p) => {
  const banner = `-- ${'─'.repeat(72)}\n-- ${p}\n-- ${'─'.repeat(72)}\n`;
  return banner + readFileSync(p, 'utf8').trim() + '\n';
}).join('\n\n');

writeFileSync(OUT, header + body);
console.log(`Wrote ${OUT} (${PARTS.length} files)`);
